name: Example C# CI Pipeline

# --------------------------------------------------
# TRIGGERS
# --------------------------------------------------

on:
  push:
    branches: [main, dev]

  pull_request:
    branches: [main, dev]


# --------------------------------------------------
# JOBS
# --------------------------------------------------

jobs:

  # Build and test the application
  build_and_test:
    name: Build and Test C# App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Cloud_Development_Unit_Test_C--main

    steps:
      # Download repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      # Restore NuGet packages
      - name: Restore Dependencies
        run: dotnet restore tests/Exercises.Tests.csproj

      # Build the application
      - name: Build Application
        run: dotnet build tests/Exercises.Tests.csproj --no-restore

      # Run tests
      - name: Run Tests
        run: dotnet test tests/Exercises.Tests.csproj --no-build --no-restore --verbosity normal


  # --------------------------------------------------
  # DEPLOY
  # --------------------------------------------------

  deploy:
    name: Deploy Our App
    needs: build_and_test
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Publish Application
        working-directory: Cloud_Development_Unit_Test_C--main
        run: dotnet publish src/Exercises.csproj -c Release -o ./publish